### ISSUE TITLE
Rule link_open

### ISSUE THREAD

**Issue by seahindeniz** [Oktavilla/markdown-it-table-of-contents#42]
Content links are not affected by the *link_open* rule whether is defined before _.use_ or after.

```js
md.renderer.rules.link_open = () => `<a class="sg-text--link sg-text--bold sg-text--blue-dark">`;
```

*Expected result:*
```html
<ul>
  <li>
    <a href="#h1-heading" class="sg-text--link sg-text--bold sg-text--blue-dark">h1 Heading</a>
  </li>
</ul>
```

*Actual result*
```html
<ul>
  <li>
    <a href="#h1-heading">h1 Heading</a>
  </li>
</ul>
```

**Comment by Morgul** [comment]
Yeah, this hit me as well. I'm trying to use this on a Nuxt.js site, and nuxt requires you to use `<nuxt-link>` tags instead of `<a>` tags so it's routing logic can handle some things for you. There's no way to make the links generate correctly without either being able to override the tag used for the links, or intercepting them with `rules.link_open` (Which is how I capture all the rest of the links on the page).

**Comment by martinlissmyr** [comment]
A PR with a fix would be most welcome! :)
